version: '3.8'
services:
  web:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
      - .:/app/

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
volumes:
  mysql_data: