version: '3.8'
services:
  web:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    volumes:
      - .:/app/